window.DanceData = {
  styles: {
    Ballet: { color: "#e89fb7", accent: "#8b3d59" },
    Tap: { color: "#c7a367", accent: "#5f4725" },
    Jazz: { color: "#ff8f5a", accent: "#7e2f10" },
    "Hip-Hop": { color: "#4c9fff", accent: "#123f76" },
    Contemporary: { color: "#67cfa0", accent: "#1f5a41" },
    Lyrical: { color: "#8dc0d6", accent: "#274d5f" },
    Acro: { color: "#e4c54f", accent: "#65520f" }
  },
  classes: [
    {
      id: "c1",
      name: "Tiny Tutus",
      ageRange: "Ages 3-5",
      style: "Ballet",
      instructor: "Mila Navarro",
      room: "Studio A",
      days: ["Mon", "Wed"],
      start: "15:30",
      end: "16:15",
      capacity: 12,
      studentIds: ["s10", "s11", "s12", "s13", "s14", "s15", "s16", "s17"]
    },
    {
      id: "c2",
      name: "Junior Jazz",
      ageRange: "Ages 9-13",
      style: "Jazz",
      instructor: "Kendra Lee",
      room: "Studio B",
      days: ["Tue", "Thu"],
      start: "16:30",
      end: "17:30",
      capacity: 15,
      studentIds: ["s3", "s4", "s5", "s6", "s7", "s8", "s9", "s18", "s19", "s20", "s21", "s22"]
    },
    {
      id: "c3",
      name: "Hip-Hop Crew",
      ageRange: "Ages 10-16",
      style: "Hip-Hop",
      instructor: "Marcus Reed",
      room: "Studio C",
      days: ["Mon", "Wed", "Fri"],
      start: "18:00",
      end: "19:00",
      capacity: 18,
      studentIds: ["s5", "s6", "s7", "s8", "s9", "s18", "s19", "s20", "s21", "s22", "s23", "s24", "s25", "s26", "s27", "s28"]
    },
    {
      id: "c4",
      name: "Pointe Technique",
      ageRange: "Ages 12+",
      style: "Ballet",
      instructor: "Elena Petrov",
      room: "Studio A",
      days: ["Tue", "Thu"],
      start: "17:45",
      end: "18:45",
      capacity: 10,
      studentIds: ["s8", "s9", "s22", "s23", "s24", "s25", "s26", "s27", "s28"]
    },
    {
      id: "c5",
      name: "Contemporary Intensive",
      ageRange: "Ages 13+",
      style: "Contemporary",
      instructor: "Sloane Kim",
      room: "Studio B",
      days: ["Mon"],
      start: "19:15",
      end: "20:45",
      capacity: 14,
      studentIds: ["s6", "s8", "s9", "s21", "s22", "s23", "s24", "s25", "s26", "s27", "s28"]
    },
    {
      id: "c6",
      name: "Tap Foundations",
      ageRange: "Ages 6-11",
      style: "Tap",
      instructor: "Jordan Blake",
      room: "Studio A",
      days: ["Sat"],
      start: "10:00",
      end: "11:00",
      capacity: 15,
      studentIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s10", "s11", "s12", "s18", "s19", "s20"]
    },
    {
      id: "c7",
      name: "Lyrical Lines",
      ageRange: "Ages 11-16",
      style: "Lyrical",
      instructor: "Ava Sinclair",
      room: "Studio B",
      days: ["Wed"],
      start: "17:00",
      end: "18:00",
      capacity: 12,
      studentIds: ["s8", "s9", "s20", "s21", "s22", "s23", "s24", "s25", "s26", "s27"]
    },
    {
      id: "c8",
      name: "Acro Basics",
      ageRange: "Ages 8-13",
      style: "Acro",
      instructor: "Liam Torres",
      room: "Studio C",
      days: ["Sat"],
      start: "11:15",
      end: "12:15",
      capacity: 14,
      studentIds: ["s4", "s5", "s6", "s7", "s8", "s9", "s18", "s19", "s20", "s21", "s22", "s23"]
    },
    {
      id: "c9",
      name: "Ballet I",
      ageRange: "Ages 6-10",
      style: "Ballet",
      instructor: "Mila Navarro",
      room: "Studio A",
      days: ["Tue", "Thu"],
      start: "15:30",
      end: "16:30",
      capacity: 16,
      studentIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s18", "s19", "s20", "s21", "s22", "s23", "s24"]
    },
    {
      id: "c10",
      name: "Recital Production",
      ageRange: "Ages 7-16",
      style: "Contemporary",
      instructor: "Faculty Team",
      room: "Main Stage",
      days: ["Fri"],
      start: "16:00",
      end: "18:00",
      capacity: 30,
      studentIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10", "s11", "s12", "s13", "s14", "s15", "s16", "s17", "s18", "s19", "s20", "s21", "s22", "s23", "s24"]
    }
  ],
  students: [
    {
      id: "s1",
      name: "Amelia Hart",
      age: 7,
      guardianName: "Nora Hart",
      phone: "(512) 555-0142",
      emergencyContact: { name: "Evan Hart", relation: "Father", phone: "(512) 555-0198" },
      classIds: ["c9", "c6", "c10"],
      membershipType: "3-Class Pack",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-05",
      notes: "Working on left split flexibility for spring showcase."
    },
    {
      id: "s2",
      name: "Chloe Ramirez",
      age: 8,
      guardianName: "Daniel Ramirez",
      phone: "(512) 555-0167",
      emergencyContact: { name: "Maya Ramirez", relation: "Mother", phone: "(512) 555-0148" },
      classIds: ["c9", "c6", "c10"],
      membershipType: "3-Class Pack",
      balance: 45,
      paymentStatus: "pending",
      packageExpires: "2026-03-02",
      notes: "Needs ankle warm-up before jumps."
    },
    {
      id: "s3",
      name: "Isla Bennett",
      age: 9,
      guardianName: "Carla Bennett",
      phone: "(512) 555-0134",
      emergencyContact: { name: "Rory Bennett", relation: "Uncle", phone: "(512) 555-0175" },
      classIds: ["c9", "c2", "c6", "c10"],
      membershipType: "Unlimited Youth",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-10",
      notes: "Strong stage presence. Cast as opening ribbon lead."
    },
    {
      id: "s4",
      name: "Harper Nguyen",
      age: 10,
      guardianName: "Linh Nguyen",
      phone: "(512) 555-0183",
      emergencyContact: { name: "Khoa Nguyen", relation: "Father", phone: "(512) 555-0133" },
      classIds: ["c9", "c2", "c6", "c8", "c10"],
      membershipType: "Unlimited Youth",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-12",
      notes: "Acro cartwheel clean; prep for aerial training."
    },
    {
      id: "s5",
      name: "Madison Clark",
      age: 11,
      guardianName: "Ariel Clark",
      phone: "(512) 555-0189",
      emergencyContact: { name: "Noah Clark", relation: "Father", phone: "(512) 555-0109" },
      classIds: ["c9", "c2", "c3", "c6", "c8", "c10"],
      membershipType: "Unlimited Youth",
      balance: 85,
      paymentStatus: "pending",
      packageExpires: "2026-03-08",
      notes: "Recovering from mild wrist strain; avoid hard floor work."
    },
    {
      id: "s6",
      name: "Zoe Patel",
      age: 12,
      guardianName: "Anika Patel",
      phone: "(512) 555-0112",
      emergencyContact: { name: "Ravi Patel", relation: "Father", phone: "(512) 555-0118" },
      classIds: ["c9", "c2", "c3", "c5", "c6", "c8", "c10"],
      membershipType: "Elite Team",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-05-01",
      notes: "Team captain candidate for hip-hop showcase."
    },
    {
      id: "s7",
      name: "Ella Simmons",
      age: 11,
      guardianName: "Tara Simmons",
      phone: "(512) 555-0105",
      emergencyContact: { name: "Jordan Simmons", relation: "Parent", phone: "(512) 555-0106" },
      classIds: ["c9", "c2", "c3", "c6", "c8", "c10"],
      membershipType: "Unlimited Youth",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-20",
      notes: "Excellent musicality in jazz combinations."
    },
    {
      id: "s8",
      name: "Riley Adams",
      age: 13,
      guardianName: "Monica Adams",
      phone: "(512) 555-0161",
      emergencyContact: { name: "Shawn Adams", relation: "Father", phone: "(512) 555-0164" },
      classIds: ["c2", "c3", "c4", "c5", "c7", "c8", "c10"],
      membershipType: "Elite Team",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-05-01",
      notes: "Assigned contemporary duet in Spring Showcase."
    },
    {
      id: "s9",
      name: "Piper Wallace",
      age: 14,
      guardianName: "Alyssa Wallace",
      phone: "(512) 555-0162",
      emergencyContact: { name: "Scott Wallace", relation: "Father", phone: "(512) 555-0169" },
      classIds: ["c2", "c3", "c4", "c5", "c7", "c8", "c10"],
      membershipType: "Elite Team",
      balance: 160,
      paymentStatus: "overdue",
      packageExpires: "2026-02-28",
      notes: "Needs modified turnout drills due to knee discomfort."
    },
    {
      id: "s10",
      name: "Lily Brooks",
      age: 5,
      guardianName: "Jamie Brooks",
      phone: "(512) 555-0129",
      emergencyContact: { name: "Alex Brooks", relation: "Parent", phone: "(512) 555-0130" },
      classIds: ["c1", "c6", "c10"],
      membershipType: "Mini Stars",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-01",
      notes: "Very shy first 10 minutes; responds to buddy system."
    },
    {
      id: "s11",
      name: "Hazel Turner",
      age: 4,
      guardianName: "Megan Turner",
      phone: "(512) 555-0181",
      emergencyContact: { name: "Chris Turner", relation: "Father", phone: "(512) 555-0182" },
      classIds: ["c1", "c6", "c10"],
      membershipType: "Mini Stars",
      balance: 30,
      paymentStatus: "pending",
      packageExpires: "2026-03-03",
      notes: "Allergy note: carries kid-safe epinephrine in front desk cabinet."
    },
    {
      id: "s12",
      name: "Grace Foster",
      age: 5,
      guardianName: "Sophie Foster",
      phone: "(512) 555-0190",
      emergencyContact: { name: "Eli Foster", relation: "Father", phone: "(512) 555-0191" },
      classIds: ["c1", "c6", "c10"],
      membershipType: "Mini Stars",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-03-30",
      notes: "Confident in recital bow sequence."
    },
    {
      id: "s13",
      name: "Mia Jennings",
      age: 4,
      guardianName: "Rachel Jennings",
      phone: "(512) 555-0122",
      emergencyContact: { name: "Paul Jennings", relation: "Father", phone: "(512) 555-0121" },
      classIds: ["c1", "c10"],
      membershipType: "Mini Stars",
      balance: 75,
      paymentStatus: "overdue",
      packageExpires: "2026-02-27",
      notes: "Recital flower role confirmed."
    },
    {
      id: "s14",
      name: "Aria Coleman",
      age: 3,
      guardianName: "Leah Coleman",
      phone: "(512) 555-0179",
      emergencyContact: { name: "Iris Coleman", relation: "Aunt", phone: "(512) 555-0178" },
      classIds: ["c1", "c10"],
      membershipType: "Mini Stars",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-15",
      notes: "Prefers front row markers."
    },
    {
      id: "s15",
      name: "Emma Price",
      age: 5,
      guardianName: "Molly Price",
      phone: "(512) 555-0141",
      emergencyContact: { name: "Dean Price", relation: "Father", phone: "(512) 555-0140" },
      classIds: ["c1", "c10"],
      membershipType: "Mini Stars",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-14",
      notes: "Quick learner, ready for level-up eval in May."
    },
    {
      id: "s16",
      name: "Sadie Kim",
      age: 4,
      guardianName: "Hannah Kim",
      phone: "(512) 555-0115",
      emergencyContact: { name: "Joon Kim", relation: "Father", phone: "(512) 555-0116" },
      classIds: ["c1", "c10"],
      membershipType: "Mini Stars",
      balance: 25,
      paymentStatus: "pending",
      packageExpires: "2026-03-11",
      notes: "Can follow full warmup without prompts."
    },
    {
      id: "s17",
      name: "Nora Diaz",
      age: 5,
      guardianName: "Carmen Diaz",
      phone: "(512) 555-0172",
      emergencyContact: { name: "Luis Diaz", relation: "Father", phone: "(512) 555-0173" },
      classIds: ["c1", "c10"],
      membershipType: "Mini Stars",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-07",
      notes: "Recently moved from beginner gymnastics."
    },
    {
      id: "s18",
      name: "Violet Hayes",
      age: 10,
      guardianName: "Holly Hayes",
      phone: "(512) 555-0154",
      emergencyContact: { name: "Mark Hayes", relation: "Father", phone: "(512) 555-0155" },
      classIds: ["c9", "c2", "c3", "c6", "c8", "c10"],
      membershipType: "Unlimited Youth",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-22",
      notes: "Comp team alternate for jazz section."
    },
    {
      id: "s19",
      name: "Scarlett Boyd",
      age: 10,
      guardianName: "Tina Boyd",
      phone: "(512) 555-0187",
      emergencyContact: { name: "Eric Boyd", relation: "Father", phone: "(512) 555-0186" },
      classIds: ["c9", "c2", "c3", "c6", "c8", "c10"],
      membershipType: "Unlimited Youth",
      balance: 95,
      paymentStatus: "overdue",
      packageExpires: "2026-03-01",
      notes: "Needs hydration reminders during long rehearsals."
    },
    {
      id: "s20",
      name: "Penelope Watts",
      age: 12,
      guardianName: "Mara Watts",
      phone: "(512) 555-0195",
      emergencyContact: { name: "Greg Watts", relation: "Father", phone: "(512) 555-0196" },
      classIds: ["c9", "c2", "c3", "c6", "c7", "c8", "c10"],
      membershipType: "Elite Team",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-05-02",
      notes: "Lead in lyrical trio."
    },
    {
      id: "s21",
      name: "Aubrey King",
      age: 13,
      guardianName: "Dani King",
      phone: "(512) 555-0138",
      emergencyContact: { name: "Micah King", relation: "Parent", phone: "(512) 555-0137" },
      classIds: ["c9", "c2", "c3", "c5", "c7", "c8", "c10"],
      membershipType: "Elite Team",
      balance: 60,
      paymentStatus: "pending",
      packageExpires: "2026-03-05",
      notes: "Goal: improve center turns consistency."
    },
    {
      id: "s22",
      name: "Layla Murphy",
      age: 13,
      guardianName: "Jenna Murphy",
      phone: "(512) 555-0125",
      emergencyContact: { name: "Tim Murphy", relation: "Father", phone: "(512) 555-0124" },
      classIds: ["c9", "c2", "c3", "c4", "c5", "c7", "c8", "c10"],
      membershipType: "Elite Team",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-05-08",
      notes: "Cast as captain in finale hip-hop section."
    },
    {
      id: "s23",
      name: "Brooklyn Shaw",
      age: 14,
      guardianName: "Casey Shaw",
      phone: "(512) 555-0159",
      emergencyContact: { name: "Ryan Shaw", relation: "Father", phone: "(512) 555-0158" },
      classIds: ["c9", "c3", "c4", "c5", "c7", "c8", "c10"],
      membershipType: "Elite Team",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-05-10",
      notes: "Strong acro tricks, prepping side aerial."
    },
    {
      id: "s24",
      name: "Savannah Moore",
      age: 15,
      guardianName: "Megan Moore",
      phone: "(512) 555-0101",
      emergencyContact: { name: "Kevin Moore", relation: "Father", phone: "(512) 555-0102" },
      classIds: ["c9", "c3", "c4", "c5", "c7", "c10"],
      membershipType: "Elite Team",
      balance: 140,
      paymentStatus: "overdue",
      packageExpires: "2026-02-26",
      notes: "Rehearsal captain for contemporary piece."
    },
    {
      id: "s25",
      name: "Camila Rhodes",
      age: 15,
      guardianName: "Paige Rhodes",
      phone: "(512) 555-0146",
      emergencyContact: { name: "Neil Rhodes", relation: "Father", phone: "(512) 555-0145" },
      classIds: ["c3", "c4", "c5", "c7"],
      membershipType: "4-Class Pack",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-28",
      notes: "Interested in assistant-teacher program next term."
    },
    {
      id: "s26",
      name: "Everly Scott",
      age: 16,
      guardianName: "Dana Scott",
      phone: "(512) 555-0110",
      emergencyContact: { name: "Glen Scott", relation: "Father", phone: "(512) 555-0111" },
      classIds: ["c3", "c4", "c5", "c7"],
      membershipType: "4-Class Pack",
      balance: 35,
      paymentStatus: "pending",
      packageExpires: "2026-03-10",
      notes: "Needs costume hem adjustment for lyrical solo."
    },
    {
      id: "s27",
      name: "Addison Lane",
      age: 14,
      guardianName: "Renee Lane",
      phone: "(512) 555-0127",
      emergencyContact: { name: "Paul Lane", relation: "Father", phone: "(512) 555-0128" },
      classIds: ["c3", "c4", "c5", "c7"],
      membershipType: "4-Class Pack",
      balance: 0,
      paymentStatus: "paid",
      packageExpires: "2026-04-18",
      notes: "Assigned understudy for pointe trio."
    },
    {
      id: "s28",
      name: "Naomi Cruz",
      age: 15,
      guardianName: "Rosa Cruz",
      phone: "(512) 555-0170",
      emergencyContact: { name: "Miguel Cruz", relation: "Father", phone: "(512) 555-0171" },
      classIds: ["c3", "c4", "c5"],
      membershipType: "3-Class Pack",
      balance: 120,
      paymentStatus: "overdue",
      packageExpires: "2026-02-25",
      notes: "Goal tracking: stronger turns from fifth."
    }
  ],
  transactions: [
    { id: "t1", date: "2026-02-01", studentId: "s1", amount: 185, type: "monthly tuition", status: "paid", method: "card" },
    { id: "t2", date: "2026-02-01", studentId: "s2", amount: 185, type: "monthly tuition", status: "pending", method: "card" },
    { id: "t3", date: "2026-02-01", studentId: "s3", amount: 220, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t4", date: "2026-02-02", studentId: "s4", amount: 220, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t5", date: "2026-02-02", studentId: "s5", amount: 220, type: "monthly tuition", status: "pending", method: "card" },
    { id: "t6", date: "2026-02-02", studentId: "s6", amount: 265, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t7", date: "2026-02-03", studentId: "s7", amount: 220, type: "monthly tuition", status: "paid", method: "card" },
    { id: "t8", date: "2026-02-03", studentId: "s8", amount: 265, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t9", date: "2026-02-03", studentId: "s9", amount: 265, type: "monthly tuition", status: "overdue", method: "card" },
    { id: "t10", date: "2026-02-04", studentId: "s10", amount: 150, type: "monthly tuition", status: "paid", method: "card" },
    { id: "t11", date: "2026-02-04", studentId: "s11", amount: 150, type: "monthly tuition", status: "pending", method: "card" },
    { id: "t12", date: "2026-02-04", studentId: "s12", amount: 150, type: "monthly tuition", status: "paid", method: "cash" },
    { id: "t13", date: "2026-02-05", studentId: "s13", amount: 135, type: "monthly tuition", status: "overdue", method: "card" },
    { id: "t14", date: "2026-02-05", studentId: "s14", amount: 135, type: "monthly tuition", status: "paid", method: "card" },
    { id: "t15", date: "2026-02-05", studentId: "s15", amount: 135, type: "monthly tuition", status: "paid", method: "card" },
    { id: "t16", date: "2026-02-06", studentId: "s16", amount: 135, type: "monthly tuition", status: "pending", method: "card" },
    { id: "t17", date: "2026-02-06", studentId: "s17", amount: 135, type: "monthly tuition", status: "paid", method: "cash" },
    { id: "t18", date: "2026-02-06", studentId: "s18", amount: 220, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t19", date: "2026-02-07", studentId: "s19", amount: 220, type: "monthly tuition", status: "overdue", method: "card" },
    { id: "t20", date: "2026-02-07", studentId: "s20", amount: 265, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t21", date: "2026-02-08", studentId: "s21", amount: 265, type: "monthly tuition", status: "pending", method: "card" },
    { id: "t22", date: "2026-02-08", studentId: "s22", amount: 265, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t23", date: "2026-02-08", studentId: "s23", amount: 265, type: "monthly tuition", status: "paid", method: "card" },
    { id: "t24", date: "2026-02-09", studentId: "s24", amount: 265, type: "monthly tuition", status: "overdue", method: "card" },
    { id: "t25", date: "2026-02-09", studentId: "s25", amount: 210, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t26", date: "2026-02-09", studentId: "s26", amount: 210, type: "monthly tuition", status: "pending", method: "card" },
    { id: "t27", date: "2026-02-10", studentId: "s27", amount: 210, type: "monthly tuition", status: "paid", method: "card" },
    { id: "t28", date: "2026-02-10", studentId: "s28", amount: 180, type: "monthly tuition", status: "overdue", method: "card" },
    { id: "t29", date: "2026-02-12", studentId: "s5", amount: 75, type: "costume fee", status: "paid", method: "card" },
    { id: "t30", date: "2026-02-12", studentId: "s9", amount: 75, type: "costume fee", status: "pending", method: "card" },
    { id: "t31", date: "2026-02-13", studentId: "s13", amount: 55, type: "recital fee", status: "pending", method: "cash" },
    { id: "t32", date: "2026-02-13", studentId: "s24", amount: 55, type: "recital fee", status: "overdue", method: "card" },
    { id: "t33", date: "2026-02-14", studentId: "s3", amount: 22, type: "drop-in", status: "paid", method: "card" },
    { id: "t34", date: "2026-02-15", studentId: "s16", amount: 22, type: "drop-in", status: "paid", method: "cash" },
    { id: "t35", date: "2026-02-16", studentId: "s19", amount: 55, type: "recital fee", status: "pending", method: "card" },
    { id: "t36", date: "2026-02-18", studentId: "s28", amount: 75, type: "costume fee", status: "overdue", method: "card" },
    { id: "t37", date: "2026-01-14", studentId: "s6", amount: 265, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t38", date: "2026-01-15", studentId: "s8", amount: 265, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t39", date: "2026-01-16", studentId: "s20", amount: 265, type: "monthly tuition", status: "paid", method: "ach" },
    { id: "t40", date: "2026-01-17", studentId: "s22", amount: 265, type: "monthly tuition", status: "paid", method: "ach" }
  ],
  events: [
    {
      id: "e1",
      name: "Spring Showcase 2026",
      date: "2026-04-18",
      venue: "Riverfront Arts Center",
      status: "On Track",
      routines: [
        { routine: "Blooming Petals", classId: "c1", costumeStatus: "Distributed" },
        { routine: "Sharp Edges", classId: "c2", costumeStatus: "Arrived" },
        { routine: "City Pulse", classId: "c3", costumeStatus: "Ordered" },
        { routine: "Afterlight", classId: "c5", costumeStatus: "Ordered" }
      ],
      rehearsals: [
        { date: "2026-03-28", time: "13:00-16:00", focus: "Full cast spacing", room: "Main Stage" },
        { date: "2026-04-04", time: "10:00-14:00", focus: "Act I clean", room: "Main Stage" },
        { date: "2026-04-11", time: "10:00-15:00", focus: "Dress rehearsal", room: "Riverfront" }
      ],
      ticketing: { sold: 188, goal: 260, price: 24 },
      fees: { expected: 3600, collected: 2880 }
    },
    {
      id: "e2",
      name: "Community Arts Night",
      date: "2026-03-14",
      venue: "Oak Street Plaza",
      status: "Planning",
      routines: [
        { routine: "Neighborhood Groove", classId: "c3", costumeStatus: "Arrived" },
        { routine: "Golden Steps", classId: "c6", costumeStatus: "Distributed" }
      ],
      rehearsals: [
        { date: "2026-03-07", time: "14:00-16:00", focus: "Outdoor spacing", room: "Studio C" },
        { date: "2026-03-12", time: "18:30-20:00", focus: "Run-through", room: "Studio A" }
      ],
      ticketing: { sold: 0, goal: 0, price: 0 },
      fees: { expected: 640, collected: 520 }
    },
    {
      id: "e3",
      name: "Summer Intensive Auditions",
      date: "2026-05-30",
      venue: "Summit Dance Loft",
      status: "Registration Open",
      routines: [
        { routine: "Technique Evaluation", classId: "c4", costumeStatus: "N/A" },
        { routine: "Contemporary Phrasework", classId: "c5", costumeStatus: "N/A" },
        { routine: "Acro Skills Pass", classId: "c8", costumeStatus: "N/A" }
      ],
      rehearsals: [
        { date: "2026-05-23", time: "12:00-15:00", focus: "Mock audition", room: "Studio B" }
      ],
      ticketing: { sold: 0, goal: 0, price: 0 },
      fees: { expected: 980, collected: 245 }
    }
  ]
};
